In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
import os

## import data

### total data

In [2]:
fpath = "F:\\DeepLearning\\Data"
fpath_insample = os.path.join(fpath, "insample")
fpath_outsample = os.path.join(fpath, "outsample")

X_train = np.load(os.path.join(fpath_insample, "X.npy"))
Y_train = np.load(os.path.join(fpath_insample, "Y.npy"))
X_test = np.load(os.path.join(fpath_outsample, "X.npy"))
Y_test = np.load(os.path.join(fpath_outsample, "Y.npy"))

In [3]:
X_train.shape

(70440, 229)

In [4]:
Y_train.shape

(70440,)

In [5]:
X_test.shape

(25500, 229)

In [6]:
Y_test.shape

(25500,)

### sample data

In [7]:
fpath_sample = "F:\\DeepLearning\\Data\\sample"

X = np.load(os.path.join(fpath_sample, "X.npy"))
Y = np.load(os.path.join(fpath_sample, "Y.npy"))
X_train = X[:800,:]
Y_train = Y[:800]
X_test = X[800:,:]
Y_test = Y[800:]

In [8]:
X_train.shape

(800, 229)

In [9]:
Y_train.shape

(800,)

In [10]:
X_test.shape

(370, 229)

In [11]:
Y_test.shape

(370,)

## run model

* LogisticRegression
* RandomForest
* SupportVectorMachine
* DNN

In [7]:
# import model 
from model import *

C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


### generate model class

#### if we begin with empty model class

In [13]:
lg = LogisticRegression(X_train, Y_train, X_test, Y_test)
rf = RandomForest(X_train, Y_train, X_test, Y_test)
svm = SupportVectorMachine(X_train, Y_train, X_test, Y_test)
dnn = DNN(X_train, Y_train, X_test, Y_test)
modelsList = [lg, rf, svm, dnn]

#### if we begin with existent model in "modelpath"

In [10]:
modelpath = "F:\\DeepLearning\\Model\\20180929-141510"

In [11]:
lg = LogisticRegression(fpath=modelpath)
rf = RandomForest(fpath=modelpath)
svm = SupportVectorMachine(fpath=modelpath)
dnn = DNN(fpath=modelpath)
modelsList = [lg, rf, svm, dnn]

### using model 

In [14]:
modelpath = os.path.join("F:\\DeepLearning\\Model", datetime.now().strftime("%Y%m%d-%H%M%S"))

In [15]:
def using_model(model):
    print("Begin Model: {}\n\n".format(model.type))
    Accuracy, Precision, Recall, F1, TPR, FPR, AUC = model.evalution()
    print("\nAccuracy, Precision, Recall, F1, TPR, FPR, AUC:")
    print(Accuracy, Precision, Recall, F1, TPR, FPR, AUC,"\n")
    
    Accuracy, Precision, Recall, F1, TPR, FPR, AUC = model.evalution_with_data(X_test, Y_test)
    print("\nAccuracy, Precision, Recall, F1, TPR, FPR, AUC:")
    print(Accuracy, Precision, Recall, F1, TPR, FPR, AUC,"\n")
    
    print("\nPredict X_test with classified output:")
    print(model.predict(X_test[0:10,:]),"\n")
    
    print("\nPredict X_test with probability output:")
    print(model.predict_proba(X_test[0:10,:]),"\n")
    
    model.save_model(modelpath)

## LogisticRegression

In [16]:
using_model(modelsList[0])

Begin Model: ModelType.LR


Epoch 1/100
800/800 [==============================] - 0s 362us/step - loss: 0.8226 - acc: 0.7363
Epoch 2/100
800/800 [==============================] - 0s 47us/step - loss: 0.7119 - acc: 0.8737
Epoch 3/100
800/800 [==============================] - 0s 41us/step - loss: 0.6372 - acc: 0.9150
Epoch 4/100
800/800 [==============================] - 0s 49us/step - loss: 0.5850 - acc: 0.9387
Epoch 5/100
800/800 [==============================] - 0s 49us/step - loss: 0.5524 - acc: 0.9400
Epoch 6/100
800/800 [==============================] - 0s 49us/step - loss: 0.5302 - acc: 0.9350
Epoch 7/100
800/800 [==============================] - 0s 51us/step - loss: 0.5129 - acc: 0.9612
Epoch 8/100
800/800 [==============================] - 0s 49us/step - loss: 0.5016 - acc: 0.9475
Epoch 9/100
800/800 [==============================] - 0s 52us/step - loss: 0.4922 - acc: 0.9500
Epoch 10/100
800/800 [==============================] - 0s 54us/step - loss: 0.4853 - acc: 0.9575


## RandomForest

In [17]:
using_model(modelsList[1])

Begin Model: ModelType.RF




[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished



Accuracy, Precision, Recall, F1, TPR, FPR, AUC:
0.9945945945945946 0.9888888888888889 1.0 0.9944134078212291 1.0 0.010416666666666666 0.9997073970037453 


Accuracy, Precision, Recall, F1, TPR, FPR, AUC:
0.9945945945945946 0.9888888888888889 1.0 0.9944134078212291 1.0 0.010416666666666666 0.9947916666666667 


Predict X_test with classified output:
[1. 1. 0. 0. 0. 1. 1. 0. 0. 0.] 


Predict X_test with probability output:
[0.99200149 0.99923482 0.         0.         0.03997481 0.9999491
 0.9999491  0.         0.         0.        ] 

The RandomForest Model save in 
  F:\DeepLearning\Model\20180929-145549\RF_model.pkl


## SupportVectorMachine

In [18]:
using_model(modelsList[2])

Begin Model: ModelType.SVM


[LibSVM]
Accuracy, Precision, Recall, F1, TPR, FPR, AUC:
0.9297297297297298 0.9 0.9606741573033708 0.9293478260869567 0.9606741573033708 0.09895833333333333 0.9801615168539326 


Accuracy, Precision, Recall, F1, TPR, FPR, AUC:
0.9216216216216216 0.8669950738916257 0.9887640449438202 0.9238845144356955 0.9887640449438202 0.140625 0.9240695224719101 


Predict X_test with classified output:
[1. 1. 0. 0. 0. 1. 1. 0. 0. 0.] 


Predict X_test with probability output:
[9.99986377e-01 9.99996505e-01 1.97228445e-05 1.00000010e-07
 1.81696418e-03 9.68966171e-01 9.95709092e-01 6.65320324e-03
 3.40073709e-03 7.50821971e-02] 

The SupportVectorMachine Model save in 
  F:\DeepLearning\Model\20180929-145549\SVM_model.pkl


## DNN

In [19]:
using_model(modelsList[3])

Begin Model: ModelType.DNN


Epoch 1/100
800/800 [==============================] - 1s 638us/step - loss: 2.9472 - acc: 0.6513
Epoch 2/100
800/800 [==============================] - 0s 86us/step - loss: 2.6443 - acc: 0.8238
Epoch 3/100
800/800 [==============================] - 0s 92us/step - loss: 2.5959 - acc: 0.8400
Epoch 4/100
800/800 [==============================] - 0s 87us/step - loss: 2.4826 - acc: 0.8638
Epoch 5/100
800/800 [==============================] - 0s 85us/step - loss: 2.4139 - acc: 0.8850
Epoch 6/100
800/800 [==============================] - 0s 80us/step - loss: 2.3813 - acc: 0.8975
Epoch 7/100
800/800 [==============================] - 0s 84us/step - loss: 2.3174 - acc: 0.8975
Epoch 8/100
800/800 [==============================] - 0s 97us/step - loss: 2.2364 - acc: 0.9287
Epoch 9/100
800/800 [==============================] - 0s 92us/step - loss: 2.2285 - acc: 0.9175
Epoch 10/100
800/800 [==============================] - 0s 94us/step - loss: 2.1782 - acc: 0.9262

In [44]:
fpath = "F:\\DeepLearning\\data\\outsample_total"
frequency = 5

In [45]:
X_portfolio = np.load(os.path.join(fpath, "factors_" + str(frequency) + "days.npy"))
Y_portfolio = np.load(os.path.join(fpath, "prices_" + str(frequency) + "days.npy"))

In [46]:
model = modelsList[3]

In [47]:
model.type

<ModelType.DNN: 3>

In [48]:
portfolios = []
portfolio_probas = []
for i in range(len(X_portfolio)):
    factors = X_portfolio[i]
    portfolio = model.predict(factors)
    portfolio_proba = model.predict_proba(factors)
    portfolios.append(portfolio)
    portfolio_probas.append(portfolio_proba)
portfolios = np.array(portfolios)
portfolio_probas = np.array(portfolio_probas)

In [49]:
portfolios.shape

(171,)

In [50]:
portfolios[0].shape

(296,)

In [55]:
portfolios[0]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0.

In [51]:
portfolio_probas.shape

(171,)

In [52]:
portfolio_probas[0].shape

(296,)

In [56]:
portfolio_probas[0]

array([0.01367685, 0.01146755, 0.6491244 , 0.08118903, 0.0157655 ,
       0.02810515, 0.0205674 , 0.01808242, 0.01703241, 0.98353463,
       0.94881743, 0.01701932, 0.08567779, 0.05326505, 0.06053116,
       0.59298104, 0.01700561, 0.9657039 , 0.01692834, 0.02973276,
       0.01717285, 0.74395263, 0.01351875, 0.01703715, 0.01561288,
       0.2944293 , 0.03630266, 0.01512188, 0.04677643, 0.9606394 ,
       0.86354727, 0.00783255, 0.01733734, 0.9340281 , 0.992145  ,
       0.63586277, 0.78100336, 0.12922242, 0.06026883, 0.04903495,
       0.89082426, 0.16718353, 0.68514013, 0.06337925, 0.9112654 ,
       0.9208965 , 0.19730078, 0.37242836, 0.52472013, 0.01668398,
       0.01969806, 0.2515435 , 0.96147114, 0.90284264, 0.01705395,
       0.96003485, 0.84241974, 0.90116113, 0.95622915, 0.01837795,
       0.01760018, 0.79733366, 0.5424491 , 0.02256664, 0.01631686,
       0.01857221, 0.01499528, 0.01710765, 0.04741203, 0.01701227,
       0.01704653, 0.9664052 , 0.9195778 , 0.04502695, 0.01584

In [53]:
np.save("predict_DNN_5days.npy", portfolios)

In [54]:
np.save("predict_proba_DNN_5days.npy", portfolio_probas)