In [1]:
import numpy as np
import pandas as pd
import os
import csv

In [113]:
fpath = "F:\\DeepLearning\\data\\csmar"
name = "mkt_data"
filepath = os.path.join(fpath, name + ".h5")

In [74]:
daily_return.shape

(1041, 729)

In [75]:
risk_free.shape

(1551, 1)

In [76]:
market_data.shape

(1041, 1)

In [512]:
trade_status = dv.get_field("trade_status")

In [513]:
trade_status.columns = pd.Series(trade_status.columns).apply(lambda x: x[:-3])

In [514]:
today_status = trade_status.loc[today]

In [515]:
today_stock = np.array([stock for stock in today_stock if today_status[stock]])

In [516]:
len(today_stock)

287

In [503]:
index_member = dv.get_field("index_member")

In [504]:
index_member.columns = pd.Series(index_member.columns).apply(lambda x: x[:-3])

In [505]:
today = 20180629

In [506]:
today_stock = index_member.columns[index_member.loc[today] == 1.0].values

In [507]:
freq = 60

In [517]:
i = np.where(daily_return.index == today)[0][0]
today_daily_return = daily_return.iloc[i - freq + 1:i + 1][today_stock]
today_mkt_return = market_data.iloc[i - freq + 1:i + 1]['mkt_return']
mean_mkt_return = np.mean(today_mkt_return)
var_mkt_return = np.var(today_mkt_return)

In [525]:
pred_data = np.concatenate((np.ones(150), np.zeros(137)))
permutation = np.random.permutation(287)
pred_data = pred_data[permutation]
P = pred_data * 2 -1

In [526]:
stock_cum_returns = {}
for stock in today_daily_return.columns:
    stock_return = today_daily_return[stock]
    stock_cum_return = stock_return.rolling(10).apply(lambda x: (x + 1).cumprod()[-1] - 1)
    stock_cum_return_done = []
    for i in range(len(stock_cum_return)):
        if i % 10 == 9:
            stock_cum_return_done.append(stock_cum_return.iloc[i])
    stock_cum_returns[stock] = stock_cum_return_done

In [527]:
stock_cum_returns = pd.DataFrame(stock_cum_returns, columns=stock_cum_returns.keys())

In [528]:
mean_cum_return = np.mean(stock_cum_returns).values

In [529]:
qqq = P * mean_cum_return

In [530]:
len(qqq)

287

In [531]:
Omega = np.var(qqq)

In [532]:
q = np.mean(qqq)

In [533]:
P = np.matrix(P)

In [557]:
def get_pi(today_stock, today_risk_free, today_mkt_return, today_daily_return):
    mean_mkt_return = np.mean(today_mkt_return)
    var_mkt_return = np.var(today_mkt_return)

    betas = []
    for stock in today_stock:
        beta = np.cov(today_daily_return[stock], today_mkt_return)
        betas.append(beta[1, 0])
    betas = np.array(betas) / var_mkt_return

    pi = betas * (mean_mkt_return - today_risk_free).values
    return np.matrix(pi).reshape(-1, 1)

In [558]:
pi = get_pi(today_stock, today_risk_free, today_mkt_return, today_daily_return)

In [536]:
cov = np.cov(today_daily_return, rowvar=False)

In [537]:
cov = np.matrix(cov)

In [551]:
(tau * cov).I.shape

(287, 287)

In [552]:
pi.shape

(1, 287)

In [540]:
first_part = ((tau * cov).I + np.matrix(np.dot(np.dot(P.T, 1/Omega), P))).I

In [563]:
second_part = np.dot((tau * cov).I, pi) + np.dot(np.dot(P.T, 1/Omega), q)

In [564]:
miu = np.dot(first_part, second_part)

In [567]:
V = first_part

In [571]:
V.shape

(287, 287)

In [572]:
miu.shape

(287, 1)

In [ ]:
V

In [589]:
delta = 0.5

In [590]:
w = np.dot((delta * V).I, miu)

In [591]:
w.shape

(287, 1)

In [592]:
np.sum(w)

-469092.0

In [323]:
aa_cum = aa.rolling(10).apply(lambda x: (x + 1).cumprod()[-1])

In [328]:
for i in range(len(aa_cum)):
    if i % 10 == 9:
        print(aa_cum.iloc[i])

0.9844053332909274
1.0712871398761747
0.9824394671561353
1.2323623841135172
1.1725205756976844
1.031248470518069


In [297]:
mean_daily_return = np.mean(today_daily_return).values

In [265]:
tau = 1

In [277]:
aa = np.matrix(tau * cov).I

In [278]:
aa * tau

matrix([[ 1268.1985885 , -1078.48956027],
        [-1078.48956027,  4555.04909813]])

In [279]:
cov

array([[0.00098732, 0.00023376],
       [0.00023376, 0.00027488]])

In [280]:
cov = np.matrix(cov)

In [274]:
np.dot(P, P.T)

matrix([[300.]])

In [283]:
(tau * cov).I

matrix([[ 1268.1985885 , -1078.48956027],
        [-1078.48956027,  4555.04909813]])

In [284]:
q

NameError: name 'q' is not defined

In [281]:
((tau * cov).I + np.dot(np.dot(P.T, P), P)).I

ValueError: shapes (300,300) and (1,300) not aligned: 300 (dim 1) != 1 (dim 0)

In [251]:
mean_daily_return1 = mean_daily_return.reshape(-1,1)

In [252]:
P1 = P.reshape(1, -1)

In [260]:
np.matrix(cov).I

matrix([[ 1268.1985885 , -1078.48956027],
        [-1078.48956027,  4555.04909813]])

In [257]:
cov.T

array([[0.00098732, 0.00023376],
       [0.00023376, 0.00027488]])

In [262]:
np.matrix(P)

matrix([[ 1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.,
          1., -1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,
          1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1., -1., -1.,
         -1., -1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,
         -1., -1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,
          1., -1., -1.,  1., -1., -1., -1., -1., -1.,  1., -1., -1., -1.,
          1., -1., -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,
          1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1., -1., -1., -1.,
         -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,
         -1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1., -1.,  1.,  1.,
         -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1., -1.,
         -1.,  1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.,  1., -1.,
         -1.,  1.,  1., -1.,  1.,  1., -1.,  1., -1., -1., -1.,  1., -1.,
         -1.,  1., -1., -1., -1., -1.,

0.00023376479320338987

In [175]:
today_daily_return[stock].shape

(60,)

In [167]:
np.cov(today_daily_return, today_mkt_return)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [162]:
np.where(market_data.index == today)[0][0]

976

In [ ]:

    today_risk_free = risk_free.loc[today]
    today_mkt_return = market_data.loc[today]

In [118]:
today

20180629

In [119]:
today_risk_free

risk_free    0.0041
Name: 20180629, dtype: float64

In [607]:
from model import *
import numpy as np
import pandas as pd
from datetime import datetime
import os
import pickle as pkl

Using TensorFlow backend.


In [594]:
with open("F:\\DeepLearning\\Model\\result_GA.pkl", "rb") as file:
    GA = pkl.load(file)

In [596]:
GA.keys()

dict_keys(['best_factors', 'best_factorsList', 'best_probs', 'best_probsList'])

In [598]:
sum(GA['best_factors'])

195.0

In [599]:
GA['best_probs']

0.02009557404826736

In [614]:
GA_factor = GA['best_factors'].astype(np.int)

In [617]:
GA_factor

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1])

In [608]:
modelpath = os.path.join("F:\\DeepLearning\\Model", datetime.now().strftime("%Y%m%d-%H%M%S"))

In [609]:
fpath = "F:\\DeepLearning\\Data"
fpath_insample = os.path.join(fpath, "insample")
fpath_outsample = os.path.join(fpath, "outsample")
X_train = np.load(os.path.join(fpath_insample, "X.npy"))
Y_train = np.load(os.path.join(fpath_insample, "Y.npy"))
X_test = np.load(os.path.join(fpath_outsample, "X.npy"))
Y_test = np.load(os.path.join(fpath_outsample, "Y.npy"))

In [625]:
X_train[:, GA_factor == 1].shape

(70380, 195)

In [626]:
X_train.shape[1]

229

In [618]:
X_train.shape

(70380, 229)

In [400]:
from dataview import DataView
import pandas as pd
import numpy as np

In [401]:
dv = DataView()

In [402]:
fff = "basic_infor"

In [403]:
fpath = "F:\\DeepLearning\\Data\\outsample\\" + fff

In [404]:
dv.load_dataview(fpath)

Dataview loaded successfully.


In [406]:
close_adj = dv.get_field("close_adj")

['000001.SZ',
 '000002.SZ',
 '000008.SZ',
 '000009.SZ',
 '000012.SZ',
 '000016.SZ',
 '000021.SZ',
 '000022.SZ',
 '000027.SZ',
 '000029.SZ',
 '000031.SZ',
 '000036.SZ',
 '000039.SZ',
 '000046.SZ',
 '000059.SZ',
 '000060.SZ',
 '000061.SZ',
 '000063.SZ',
 '000066.SZ',
 '000068.SZ',
 '000069.SZ',
 '000088.SZ',
 '000089.SZ',
 '000096.SZ',
 '000099.SZ',
 '000100.SZ',
 '000156.SZ',
 '000157.SZ',
 '000166.SZ',
 '000301.SZ',
 '000333.SZ',
 '000338.SZ',
 '000400.SZ',
 '000401.SZ',
 '000402.SZ',
 '000410.SZ',
 '000413.SZ',
 '000415.SZ',
 '000420.SZ',
 '000422.SZ',
 '000423.SZ',
 '000425.SZ',
 '000429.SZ',
 '000488.SZ',
 '000498.SZ',
 '000503.SZ',
 '000507.SZ',
 '000518.SZ',
 '000520.SZ',
 '000528.SZ',
 '000532.SZ',
 '000533.SZ',
 '000536.SZ',
 '000538.SZ',
 '000539.SZ',
 '000540.SZ',
 '000541.SZ',
 '000543.SZ',
 '000550.SZ',
 '000555.SZ',
 '000559.SZ',
 '000568.SZ',
 '000571.SZ',
 '000572.SZ',
 '000573.SZ',
 '000581.SZ',
 '000596.SZ',
 '000598.SZ',
 '000599.SZ',
 '000601.SZ',
 '000607.SZ',
 '0006

In [12]:
df = pd.read_hdf("F:\\DeepLearning\\csmar\\risk_free_rate.h5")

In [13]:
df

统计日期  无风险利率(%)  日度化无风险利率(%)  周度化无风险利率(%)  月度化无风险利率(%)
0      1990-04-15     10.08       0.0263       0.1849       0.8035
1      1990-08-21      8.64       0.0227       0.1595       0.6930
2      1990-12-19      8.64       0.0227       0.1595       0.6930
3      1990-12-20      8.64       0.0227       0.1595       0.6930
4      1990-12-21      8.64       0.0227       0.1595       0.6930
5      1990-12-22      8.64       0.0227       0.1595       0.6930
6      1990-12-23      8.64       0.0227       0.1595       0.6930
7      1990-12-24      8.64       0.0227       0.1595       0.6930
8      1990-12-25      8.64       0.0227       0.1595       0.6930
9      1990-12-26      8.64       0.0227       0.1595       0.6930
10     1990-12-27      8.64       0.0227       0.1595       0.6930
11     1990-12-28      8.64       0.0227       0.1595       0.6930
12     1990-12-29      8.64       0.0227       0.1595       0.6930
13     1990-12-30      8.64       0.0227       0.1595       0.6930
14     1990-12-31      8.64       0.0227       0.1595       0.6930
15     1991-01-01      8.64       0.0227       0.1595       0.6930
16     1991-01-02      8.64       0.0227       0.1595       0.6930
17     1991-01-03      8.64       0.0227       0.1595       0.6930
18     1991-01-04      8.64       0.0227       0.1595       0.6930
19     1991-01-05      8.64       0.0227       0.1595       0.6930
20     1991-01-06      8.64       0.0227       0.1595       0.6930
21     1991-01-07      8.64       0.0227       0.1595       0.6930
22     1991-01-08      8.64       0.0227       0.1595       0.6930
23     1991-01-09      8.64       0.0227       0.1595       0.6930
24     1991-01-10      8.64       0.0227       0.1595       0.6930
25     1991-01-11      8.64       0.0227       0.1595       0.6930
26     1991-01-12      8.64       0.0227       0.1595       0.6930
27     1991-01-13      8.64       0.0227       0.1595       0.6930
28     1991-01-14      8.64       0.0227       0.1595       0.6930
29     1991-01-15      8.64       0.0227       0.1595       0.6930
...           ...       ...          ...          ...          ...
10104  2018-08-16      1.50       0.0041       0.0286       0.1241
10105  2018-08-17      1.50       0.0041       0.0286       0.1241
10106  2018-08-18      1.50       0.0041       0.0286       0.1241
10107  2018-08-19      1.50       0.0041       0.0286       0.1241
10108  2018-08-20      1.50       0.0041       0.0286       0.1241
10109  2018-08-21      1.50       0.0041       0.0286       0.1241
10110  2018-08-22      1.50       0.0041       0.0286       0.1241
10111  2018-08-23      1.50       0.0041       0.0286       0.1241
10112  2018-08-24      1.50       0.0041       0.0286       0.1241
10113  2018-08-25      1.50       0.0041       0.0286       0.1241
10114  2018-08-26      1.50       0.0041       0.0286       0.1241
10115  2018-08-27      1.50       0.0041       0.0286       0.1241
10116  2018-08-28      1.50       0.0041       0.0286       0.1241
10117  2018-08-29      1.50       0.0041       0.0286       0.1241
10118  2018-08-30      1.50       0.0041       0.0286       0.1241
10119  2018-08-31      1.50       0.0041       0.0286       0.1241
10120  2018-09-01      1.50       0.0041       0.0286       0.1241
10121  2018-09-02      1.50       0.0041       0.0286       0.1241
10122  2018-09-03      1.50       0.0041       0.0286       0.1241
10123  2018-09-04      1.50       0.0041       0.0286       0.1241
10124  2018-09-05      1.50       0.0041       0.0286       0.1241
10125  2018-09-06      1.50       0.0041       0.0286       0.1241
10126  2018-09-07      1.50       0.0041       0.0286       0.1241
10127  2018-09-08      1.50       0.0041       0.0286       0.1241
10128  2018-09-09      1.50       0.0041       0.0286       0.1241
10129  2018-09-10      1.50       0.0041       0.0286       0.1241
10130  2018-09-11      1.50       0.0041       0.0286       0.1241
10131  2018-09-12      1.50       0.0041       0.0286       

In [9]:
dv.get_field("index_member")

symbols     000001.SZ  000002.SZ  000008.SZ  000009.SZ  000012.SZ  000016.SZ  \
trade_date                                                                     
20141231          1.0        1.0        0.0        1.0        0.0        0.0   
20150105          1.0        1.0        0.0        1.0        0.0        0.0   
20150106          1.0        1.0        0.0        1.0        0.0        0.0   
20150107          1.0        1.0        0.0        1.0        0.0        0.0   
20150108          1.0        1.0        0.0        1.0        0.0        0.0   
20150109          1.0        1.0        0.0        1.0        0.0        0.0   
20150112          1.0        1.0        0.0        1.0        0.0        0.0   
20150113          1.0        1.0        0.0        1.0        0.0        0.0   
20150114          1.0        1.0        0.0        1.0        0.0        0.0   
20150115          1.0        1.0        0.0        1.0        0.0        0.0   
20150116          1.0        1.0        0.0        1.0        0.0        0.0   
20150119          1.0        1.0        0.0        1.0        0.0        0.0   
20150120          1.0        1.0        0.0        1.0        0.0        0.0   
20150121          1.0        1.0        0.0        1.0        0.0        0.0   
20150122          1.0        1.0        0.0        1.0        0.0        0.0   
20150123          1.0        1.0        0.0        1.0        0.0        0.0   
20150126          1.0        1.0        0.0        1.0        0.0        0.0   
20150127          1.0        1.0        0.0        1.0        0.0        0.0   
20150128          1.0        1.0        0.0        1.0        0.0        0.0   
20150129          1.0        1.0        0.0        1.0        0.0        0.0   
20150130          1.0        1.0        0.0        1.0        0.0        0.0   
20150202          1.0        1.0        0.0        1.0        0.0        0.0   
20150203          1.0        1.0        0.0        1.0        0.0        0.0   
20150204          1.0        1.0        0.0        1.0        0.0        0.0   
20150205          1.0        1.0        0.0        1.0        0.0        0.0   
20150206          1.0        1.0        0.0        1.0        0.0        0.0   
20150209          1.0        1.0        0.0        1.0        0.0        0.0   
20150210          1.0        1.0        0.0        1.0        0.0        0.0   
20150211          1.0        1.0        0.0        1.0        0.0        0.0   
20150212          1.0        1.0        0.0        1.0        0.0        0.0   
...               ...        ...        ...        ...        ...        ...   
20180518          1.0        1.0        1.0        0.0        0.0        0.0   
20180521          1.0        1.0        1.0        0.0        0.0        0.0   
20180522          1.0        1.0        1.0        0.0        0.0        0.0   
20180523          1.0        1.0        1.0        0.0        0.0        0.0   
20180524          1.0        1.0        1.0        0.0        0.0        0.0   
20180525          1.0        1.0        1.0        0.0        0.0        0.0   
20180528          1.0        1.0        1.0        0.0        0.0        0.0   
20180529          1.0        1.0        1.0        0.0        0.0        0.0   
20180530          1.0        1.0        1.0        0.0        0.0        0.0   
20180531          1.0        1.0        1.0        0.0        0.0        0.0   
20180601          1.0        1.0        1.0        0.0        0.0        0.0   
20180604          1.0        1.0        1.0        0.0        0.0        0.0   
20180605          1.0        1.0        1.0        0.0        0.0        0.0   
20180606          1.0        1.0        1.0        0.0        0.0        0.0   
20180607          1.0        1.0        1.0        0.0        0.0        0.0   
20180608          1.0        1.0        0.0        0.0        0.0        0.0   
20180611          1.0        1.0        0.0        0.0        0.0        0.0   


In [18]:
dv.get_field("close_adj").index

Int64Index([20041231, 20050104, 20050105, 20050106, 20050107, 20050110,
            20050111, 20050112, 20050113, 20050114,
            ...
            20141218, 20141219, 20141222, 20141223, 20141224, 20141225,
            20141226, 20141229, 20141230, 20141231],
           dtype='int64', name='trade_date', length=2428)

In [19]:
dv.fields

['close_adj',
 'vwap_adj',
 'index_weight',
 'volume',
 'index_member',
 'turnover',
 'high_adj',
 'open_adj',
 'trade_status',
 'low_adj']

In [34]:
np.sum(aaa, axis=1).index[63]

20050411

In [ ]:
dv.reflash_data(start_date=20050101)

In [60]:
dv.data_d = pd.merge(dv.data_d, dvnew.data_d, left_index=True, right_index=True, how='left')

In [61]:
dv.data_d = dv.data_d.sort_index(axis=1)

In [65]:
dv.fields = dv.data_d.columns.levels[1].tolist()

In [66]:
fpath = "F:\\DeepLearning\\Data\\outsample\\"

In [67]:
dv.save_dataview(fpath)

Dataview has been successfully saved to:
F:\DeepLearning\Data\outsample


In [92]:
# start_date = 20041231
# end_date = 20141231

In [93]:
start_date = 20141231
end_date = 20180701

In [94]:
dv.reflash_data(start_date=start_date, end_date=end_date)

In [95]:
fsavepath = "F:\\DeepLearning\\Data\\outsample\\" + fff

In [96]:
dv.save_dataview(fsavepath)

Dataview has been successfully saved to:
F:\DeepLearning\Data\outsample\finIndicator


In [55]:
fpath = "F:\\DeepLearning\\Data\\outsample\\technical_index"  

In [56]:
dvnew = DataView()

In [57]:
dvnew.load_dataview(fpath)

Dataview loaded successfully.


In [9]:
fin_indicator = "eps_basic_daily,eps_diluted,grps,orps,surpluscapitalps,surplusreserveps,undistributedps,extraordinary,deductedprofit,grossmargin,current,quick,cashratio,invturndays,arturndays,invturn,arturn,caturn,faturn,assetsturn,operateincome,investincome,ebit_daily,ebitda,fcff,fcfe,exinterestdebt_current,exinterestdebt_noncurrent,interestdebt,netdebt,tangibleasset,workingcapital,networkingcapital,investcapital,retainedearnings,eps_diluted2,bps,ocfps,retainedps,cfps,ebitps,fcffps,fcfeps,netprofitmargin,grossprofitmargin,cogstosales,expensetosales,profittogr,saleexpensetogr,adminexpensetogr,finaexpensetogr,impairtogr_ttm,gctogr,optogr,ebittogr,roe,waa_roe,roe_deducted,roa,roic,roe_yearly,roa2,roe_avg,operateincometoebt,investincometoebt,nonoperateprofittoebt,taxtoebt,deductedprofittoprofit,salescashintoor,ocftoor,ocftooperateincome,capitalizedtoda,debttoassets,assetstoequity,dupont_assetstoequity,catoassets,ncatoassets,tangibleassetstoassets,intdebttototalcap,equitytototalcapital,currentdebttodebt,longdebtodebt,ocftoshortdebt,debttoequity,equitytodebt,equitytointerestdebt,tangibleassettodebt,tangassettointdebt,ocftodebt,ocftointerestdebt,ocftonetdebt,ebittointerest,longdebttoworkingcapital,ebitdatodebt,turndays,roa_yearly,dupont_roa,prefinexpense_opprofit,nonopprofit,optodebt,noptoebt,ocftoprofit,cashtoliqdebt,cashtoliqdebtwithinterest,optoliqdebt,optodebt,roic_yearly,tot_faturn,profittoop,yoyeps_basic,yoyeps_diluted,yoyocfps,yoyop,yoyebt,yoynetprofit,yoynetprofit_deducted,yoyocf,yoyroe,yoybps,yoyassets,yoyequity,yoy_tr,yoy_or,yoy_equity,rd_expense"
fin_indicator = fin_indicator.split(",")

In [21]:
fin_indicator

['eps_basic_daily',
 'eps_diluted',
 'grps',
 'orps',
 'surpluscapitalps',
 'surplusreserveps',
 'undistributedps',
 'extraordinary',
 'deductedprofit',
 'grossmargin',
 'current',
 'quick',
 'cashratio',
 'invturndays',
 'arturndays',
 'invturn',
 'arturn',
 'caturn',
 'faturn',
 'assetsturn',
 'operateincome',
 'investincome',
 'ebit_daily',
 'ebitda',
 'fcff',
 'fcfe',
 'exinterestdebt_current',
 'exinterestdebt_noncurrent',
 'interestdebt',
 'netdebt',
 'tangibleasset',
 'workingcapital',
 'networkingcapital',
 'investcapital',
 'retainedearnings',
 'eps_diluted2',
 'bps',
 'ocfps',
 'retainedps',
 'cfps',
 'ebitps',
 'fcffps',
 'fcfeps',
 'netprofitmargin',
 'grossprofitmargin',
 'cogstosales',
 'expensetosales',
 'profittogr',
 'saleexpensetogr',
 'adminexpensetogr',
 'finaexpensetogr',
 'impairtogr_ttm',
 'gctogr',
 'optogr',
 'ebittogr',
 'roe',
 'waa_roe',
 'roe_deducted',
 'roa',
 'roic',
 'roe_yearly',
 'roa2',
 'roe_avg',
 'operateincometoebt',
 'investincometoebt',
 'nonop

In [22]:
len(fin_indicator)

125

In [58]:
len(dv.fields)

123

In [59]:
len(dvnew.fields)

106

In [16]:
for i in dv.data_d.columns.levels[1]:
    if i not in fin_indicator:
        print(i)

In [17]:
for i in fin_indicator:
    if i not in dv.data_d.columns.levels[1]:
        print(i)

fcff


In [128]:
name = "fcff"

In [123]:
name in dvnew.fields

True

In [125]:
df = dvnew.get_field(name)

In [126]:
dv.append_df(df,name)

In [131]:
dvnew.save_dataview(fpath)

Dataview has been successfully saved to:
F:\DeepLearning\python\JAQS_Data\000300.SH\lb.finIndicator2
